name: tracker_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  trident_tracker:
    git:
      url: https://github.com/sha158/trident_tracker.git
      ref: main
  onesignal_reusable:
    path: ./onesignal_reusable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/asset/car.png
